openapi: 3.0.0
info:
  title: Backend API
  description: API for the backend service in the monorepo
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the backend service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    example: "2025-12-30T10:00:00Z"
  /api/docs:
    get:
      summary: API Documentation
      description: Returns API documentation
      responses:
        '200':
          description: API documentation
          content:
            application/json:
              schema:
                type: object
                properties:
                  endpoints:
                    type: array
                    items:
                      type: string
                      example: "/health"