"""add chat tables

Revision ID: 33e6084bd4b2
Revises: 44293234eded
Create Date: 2026-01-21 03:37:18.561986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e6084bd4b2'
down_revision = '44293234eded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('chunks', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chunks', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('citations', 'message_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingestion_jobs', 'document_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('citations', 'message_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chunks', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('chunks', 'document_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###