"""Initial SQLite-compatible schema

Revision ID: 44293234eded
Revises: 
Create Date: 2026-01-11 03:22:03.519832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44293234eded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(36), nullable=False),  # UUID as string
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),  # UUID as string
    sa.Column('created_at', sa.DateTime(), nullable=False),  # SQLite doesn't support timezone
    sa.Column('updated_at', sa.DateTime(), nullable=False),  # SQLite doesn't support timezone
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('documents',
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('checksum', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),  # UUID as string
    sa.Column('created_at', sa.DateTime(), nullable=False),  # SQLite doesn't support timezone
    sa.Column('updated_at', sa.DateTime(), nullable=False),  # SQLite doesn't support timezone
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_path')
    )
    op.create_table('chat_messages',
    sa.Column('session_id', sa.String(36), nullable=False),  # UUID as string
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),  # UUID as string
    sa.Column('created_at', sa.DateTime(), nullable=False),  # SQLite doesn't support timezone
    sa.Column('updated_at', sa.DateTime(), nullable=False),  # SQLite doesn't support timezone
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('document_id', sa.String(36), nullable=False),  # UUID as string
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_hash', sa.String(length=100), nullable=False),
    sa.Column('vector', sa.Text(), nullable=True),
    sa.Column('chunk_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),  # UUID as string
    sa.Column('created_at', sa.DateTime(), nullable=False),  # SQLite doesn't support timezone
    sa.Column('updated_at', sa.DateTime(), nullable=False),  # SQLite doesn't support timezone
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_hash')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(36), nullable=False),  # UUID as string
    sa.Column('document_id', sa.String(36), nullable=False),  # UUID as string
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('processed_chunks', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_document_id'), 'ingestion_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('citations',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citations')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_document_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('chunks')
    op.drop_table('chat_messages')
    op.drop_table('documents')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###