openapi: 3.0.0
info:
  title: RAG Retrieval API
  version: 1.0.0
  description: API for Retrieval-Augmented Generation queries on book content

paths:
  /api/rag/query:
    post:
      summary: Query the RAG system with a question
      description: Submit a question to retrieve relevant book content and generate a grounded response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful query response with grounded answer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid query request
        '500':
          description: Internal server error during retrieval or generation

components:
  schemas:
    QueryRequest:
      type: object
      properties:
        question:
          type: string
          description: The question to be answered using book content
          example: "What are the key concepts covered in Chapter 3?"
        top_k:
          type: integer
          description: Number of top results to retrieve (default: 5)
          minimum: 1
          maximum: 20
          example: 5
        include_citations:
          type: boolean
          description: Whether to include citations in the response (default: true)
          example: true
        similarity_threshold:
          type: number
          description: Minimum similarity score for inclusion (default: 0.5)
          minimum: 0.0
          maximum: 1.0
          example: 0.5
      required:
        - question

    QueryResponse:
      type: object
      properties:
        query_id:
          type: string
          format: uuid
          description: Unique identifier for this query
        answer:
          type: string
          description: The generated answer grounded in book content
        citations:
          type: array
          items:
            $ref: '#/components/schemas/Citation'
        retrieved_chunks:
          type: array
          items:
            $ref: '#/components/schemas/RetrievedChunk'
        confidence_score:
          type: number
          description: Overall confidence in the answer (0.0-1.0)
        processing_time_ms:
          type: number
          description: Time taken to process the query in milliseconds

    Citation:
      type: object
      properties:
        chunk_id:
          type: string
          format: uuid
          description: ID of the cited chunk
        source_path:
          type: string
          description: Path to the source document
        heading:
          type: string
          description: Heading where the cited content appears
        chunk_index:
          type: integer
          description: Index of the chunk in the document
        content_preview:
          type: string
          description: Preview of the cited content

    RetrievedChunk:
      type: object
      properties:
        chunk_id:
          type: string
          format: uuid
          description: Unique identifier for the chunk
        content:
          type: string
          description: The text content of the chunk
        source_path:
          type: string
          description: Path to the source document
        chunk_index:
          type: integer
          description: Index of this chunk in the document
        confidence_score:
          type: number
          description: Similarity score for this chunk (0.0-1.0)
        metadata:
          type: object
          description: Additional metadata about the chunk